"""Generate WordPress WXR 1.2 XML export files."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import UTC, datetime
from email.utils import format_datetime


@dataclass
class WXRPost:
    """Data for a single WordPress post to export."""

    title: str
    content_html: str
    author: str = "admin"
    status: str = "draft"
    post_date: datetime | None = None
    excerpt: str = ""
    site_url: str = "https://example.com"

    # Auto-generated from title if not provided
    slug: str = ""

    def __post_init__(self) -> None:
        if self.post_date is None:
            self.post_date = datetime.now(UTC)
        if not self.slug:
            self.slug = _slugify(self.title)
        if not self.excerpt:
            self.excerpt = _extract_excerpt(self.content_html)


def generate_wxr(post: WXRPost) -> str:
    """Generate a complete WXR 1.2 XML string for a single post."""
    assert post.post_date is not None
    date_rfc2822 = format_datetime(post.post_date, usegmt=True)
    date_wp = post.post_date.strftime("%Y-%m-%d %H:%M:%S")
    date_created = post.post_date.strftime("%Y-%m-%d %H:%M")

    return _WXR_TEMPLATE.format(
        date_created=date_created,
        site_title=_escape_xml(post.title),
        site_url=post.site_url,
        pub_date=date_rfc2822,
        author=post.author,
        title=post.title,
        slug=post.slug,
        status=post.status,
        content_html=post.content_html,
        excerpt=post.excerpt,
        date_wp=date_wp,
    )


def _slugify(text: str) -> str:
    """Convert text to a URL-safe slug."""
    slug = text.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = slug.strip("-")
    return slug


def _extract_excerpt(html: str, max_chars: int = 300) -> str:
    """Extract a plain-text excerpt from HTML content."""
    text = re.sub(r"<[^>]+>", "", html)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= max_chars:
        return text
    truncated = text[:max_chars]
    last_space = truncated.rfind(" ")
    if last_space > 0:
        truncated = truncated[:last_space]
    return truncated


def _escape_xml(text: str) -> str:
    """Escape text for use in XML element content (outside CDATA)."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


_WXR_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="md2wxr/0.1.0" created="{date_created}" -->
<rss version="2.0"
\txmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
\txmlns:content="http://purl.org/rss/1.0/modules/content/"
\txmlns:wfw="http://wellformedweb.org/CommentAPI/"
\txmlns:dc="http://purl.org/dc/elements/1.1/"
\txmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
\t<title>{site_title}</title>
\t<link>{site_url}</link>
\t<description></description>
\t<pubDate>{pub_date}</pubDate>
\t<language>en-US</language>
\t<wp:wxr_version>1.2</wp:wxr_version>
\t<wp:base_site_url>{site_url}</wp:base_site_url>
\t<wp:base_blog_url>{site_url}</wp:base_blog_url>

\t<wp:author>
\t\t<wp:author_id>1</wp:author_id>
\t\t<wp:author_login><![CDATA[{author}]]></wp:author_login>
\t\t<wp:author_email><![CDATA[{author}@example.com]]></wp:author_email>
\t\t<wp:author_display_name><![CDATA[{author}]]></wp:author_display_name>
\t\t<wp:author_first_name><![CDATA[]]></wp:author_first_name>
\t\t<wp:author_last_name><![CDATA[]]></wp:author_last_name>
\t</wp:author>

\t<item>
\t\t<title><![CDATA[{title}]]></title>
\t\t<link>{site_url}/?p=1</link>
\t\t<pubDate>{pub_date}</pubDate>
\t\t<dc:creator><![CDATA[{author}]]></dc:creator>
\t\t<guid isPermaLink="false">{site_url}/?p=1</guid>
\t\t<description></description>
\t\t<content:encoded><![CDATA[{content_html}]]></content:encoded>
\t\t<excerpt:encoded><![CDATA[{excerpt}]]></excerpt:encoded>
\t\t<wp:post_id>1</wp:post_id>
\t\t<wp:post_date><![CDATA[{date_wp}]]></wp:post_date>
\t\t<wp:post_date_gmt><![CDATA[{date_wp}]]></wp:post_date_gmt>
\t\t<wp:post_modified><![CDATA[{date_wp}]]></wp:post_modified>
\t\t<wp:post_modified_gmt><![CDATA[{date_wp}]]></wp:post_modified_gmt>
\t\t<wp:comment_status><![CDATA[open]]></wp:comment_status>
\t\t<wp:ping_status><![CDATA[open]]></wp:ping_status>
\t\t<wp:post_name><![CDATA[{slug}]]></wp:post_name>
\t\t<wp:status><![CDATA[{status}]]></wp:status>
\t\t<wp:post_parent>0</wp:post_parent>
\t\t<wp:menu_order>0</wp:menu_order>
\t\t<wp:post_type><![CDATA[post]]></wp:post_type>
\t\t<wp:post_password><![CDATA[]]></wp:post_password>
\t\t<wp:is_sticky>0</wp:is_sticky>
\t</item>
</channel>
</rss>
"""
